spring.application.name=demo

# ===============================
# = DATABASE CONNECTION CONFIG =
# ===============================
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.xmefykeeegomqswqpkjt
spring.datasource.password=Evolve@2025

# Optional: PostgreSQL driver (auto-detected in most cases)
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# = JPA / HIBERNATE SETTINGS =
# ==============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
